FROM almalinux:9
ARG version=2.1
ARG ENVIRONMENT=PROD

ENV NAME=Reshwanth
ENV version=${version}|
RUN echo "name is ${NAME}"
ARG version
RUN echo "Build Docker image version: ${version}, Name is ${NAME}"
