ARG version=9
FROM almalinux:${version}
RUN echo "Print the ${version}" > resh.txt
ENV name="Reshwanth" \
    learning="Devops" \
    role="devops eng"
RUN echo "${name}, ${learning}, ${role}" > resh1.txt
